api = "0.7"

[buildpack]
id = "com.example.gradle-sidecar"
version = "0.0.1"
name = "Gradle Sidecar Buildpack"
description = "Builds a Gradle app as a sidecar process for Heroku"

[[stacks]]
id = "heroku-22"

[[targets]]
os = "linux"
